version: "3"

services:
    fluentd:
        build: ./docker/fluentd
        volumes:
            - ./fluentd/config:/fluentd/etc
        links:
            - elasticsearch
        ports:
            - "24224:24224"
        depends_on:
            - elasticsearch

    elasticsearch:
        build: ./docker/elasticsearch
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - "9200:9200"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./elasticsearch/data:/usr/share/elasticsearch/data

    kibana:
        build: ./docker/kibana
        ports:
            - "5601:5601"
        links:
            - elasticsearch:elasticsearch


