version: "3"

services:
    db:
        image: mysql:8.0.0
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
    db2:
        image: mysql:8.0.0
        container_name: db2
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
        ports:
            - 3307:3306
        volumes:
            - ./mysql2:/var/lib/mysql
    elasticsearch:
        build: ./docker/elasticsearch
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - "9200:9200"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./elasticsearch/data:/usr/share/elasticsearch/data
    fluentd:
        build: ./docker/fluentd
        # volumes:
        #     - ./fluentd/fluentd.conf:/fluentd/etc
        links:
            - elasticsearch
        ports:
            - "24224:24224"
        depends_on:
            - elasticsearch

    kibana:
        build: ./docker/kibana
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200


